import { appendFile, mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { ChatMessage } from "../application/modelProtocol";
import type { ArtifactReference, CheckpointReference, SessionEventRecord, SessionLogRecord, SessionState, SessionStore, SessionTaskState, SessionSnapshot } from "../application/sessionPersistence";
import type { SessionInfo } from "../application/workspaceService";

export class FileSessionRepository implements SessionStore {
  public async load(root: string, session: SessionInfo): Promise<SessionSnapshot> {
    const directory = sessionDirectory(root, session);
    const [config, state, messages, events, logs, artifacts, checkpoints, tasks] = await Promise.all([readJsonObject(path.join(directory, "config.json")), readJsonObject(path.join(directory, "state.json")), readJsonLines<ChatMessage>(path.join(directory, "conversation.jsonl")), readJsonLines<SessionEventRecord>(path.join(directory, "events.jsonl")), readJsonLines<SessionLogRecord>(path.join(directory, "logs.jsonl")), readJsonLines<ArtifactReference>(path.join(directory, "artifacts.jsonl")), readJsonLines<CheckpointReference>(path.join(directory, "checkpoints", "index.jsonl")), readTaskStates(path.join(directory, "tasks"))]);
    return { session, config, messages, state: normalizeSessionState(state, session.createdAt), tasks, events, logs, artifacts, checkpoints };
  }
  public appendMessage(root: string, session: SessionInfo, message: ChatMessage): Promise<void> { return appendJsonLine(path.join(sessionDirectory(root, session), "conversation.jsonl"), message); }
  public writeConfig(root: string, session: SessionInfo, config: Record<string, unknown>): Promise<void> { return writeJson(path.join(sessionDirectory(root, session), "config.json"), config); }
  public async writeTaskState(root: string, session: SessionInfo, task: SessionTaskState): Promise<void> { const directory = sessionDirectory(root, session); await writeJson(path.join(directory, "tasks", task.taskId, "state.json"), task); const status: SessionStatusForState = task.status === "running" ? "running" : task.status; await writeJson(path.join(directory, "state.json"), { status, activeTaskId: status === "running" ? task.taskId : null, updatedAt: task.updatedAt, ...(task.error ? { stopReason: task.error.message } : {}) }); }
  public appendEvent(root: string, session: SessionInfo, event: SessionEventRecord): Promise<void> { return appendJsonLine(path.join(sessionDirectory(root, session), "events.jsonl"), event); }
  public appendLog(root: string, session: SessionInfo, log: SessionLogRecord): Promise<void> { return appendJsonLine(path.join(sessionDirectory(root, session), "logs.jsonl"), log); }
  public appendArtifact(root: string, session: SessionInfo, artifact: ArtifactReference): Promise<void> { return appendJsonLine(path.join(sessionDirectory(root, session), "artifacts.jsonl"), artifact); }
  public async writeCheckpoint(root: string, session: SessionInfo, checkpoint: CheckpointReference, payload: unknown, markdown?: string): Promise<void> { const directory = sessionDirectory(root, session); await writeJson(path.join(directory, "checkpoints", `${checkpoint.checkpointId}.json`), payload); if (markdown) await writeFile(path.join(directory, "checkpoints", `${checkpoint.checkpointId}.md`), markdown, "utf8"); await appendJsonLine(path.join(directory, "checkpoints", "index.jsonl"), checkpoint); }
}

export function sessionDirectory(root: string, session: SessionInfo): string { const resolvedRoot = path.resolve(root); const directory = path.resolve(root, session.relativePath); if (directory !== resolvedRoot && !directory.startsWith(`${resolvedRoot}${path.sep}`)) throw new Error("session path escapes workspace root"); return directory; }
export async function initializeSessionFiles(root: string, session: SessionInfo): Promise<void> { const directory = sessionDirectory(root, session); await Promise.all([mkdir(path.join(directory, "tasks"), { recursive: true }), mkdir(path.join(directory, "checkpoints"), { recursive: true }), appendFile(path.join(directory, "conversation.jsonl"), "", "utf8"), appendFile(path.join(directory, "events.jsonl"), "", "utf8"), appendFile(path.join(directory, "logs.jsonl"), "", "utf8"), appendFile(path.join(directory, "artifacts.jsonl"), "", "utf8"), writeJson(path.join(directory, "config.json"), {}), writeJson(path.join(directory, "state.json"), { status: "idle", activeTaskId: null, updatedAt: session.createdAt })]); }

type SessionStatusForState = "idle" | "running" | "stopped" | "completed" | "failed";
function normalizeSessionState(value: Record<string, unknown>, createdAt: string): SessionState { const status = ["idle", "running", "stopped", "completed", "failed"].includes(String(value.status)) ? String(value.status) as SessionStatusForState : "idle"; return { status, activeTaskId: typeof value.activeTaskId === "string" ? value.activeTaskId : null, updatedAt: typeof value.updatedAt === "string" ? value.updatedAt : createdAt, ...(typeof value.stopReason === "string" ? { stopReason: value.stopReason } : {}) }; }
async function readTaskStates(directory: string): Promise<SessionTaskState[]> { let entries; try { entries = await readdir(directory, { withFileTypes: true }); } catch (error) { if (isMissing(error)) return []; throw error; } const tasks: SessionTaskState[] = []; for (const entry of entries.filter((item) => item.isDirectory())) { const task = await readJsonObject(path.join(directory, entry.name, "state.json")); if (typeof task.taskId === "string" && typeof task.status === "string") tasks.push(task as unknown as SessionTaskState); } return tasks.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)); }
async function readJsonLines<T>(file: string): Promise<T[]> { let text: string; try { text = await readFile(file, "utf8"); } catch (error) { if (isMissing(error)) return []; throw error; } return text.split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as T); }
async function readJsonObject(file: string): Promise<Record<string, unknown>> { try { return JSON.parse(await readFile(file, "utf8")) as Record<string, unknown>; } catch (error) { if (isMissing(error)) return {}; throw error; } }
async function appendJsonLine(file: string, value: unknown): Promise<void> { await mkdir(path.dirname(file), { recursive: true }); await appendFile(file, `${JSON.stringify(value)}\n`, "utf8"); }
async function writeJson(file: string, value: unknown): Promise<void> { await mkdir(path.dirname(file), { recursive: true }); const temporary = `${file}.${randomUUID()}.tmp`; await writeFile(temporary, JSON.stringify(value, null, 2), "utf8"); await rename(temporary, file); }
function isMissing(error: unknown): boolean { return error instanceof Error && "code" in error && error.code === "ENOENT"; }
